src/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'publics#home', as: "home"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :instructors
  resources :students
  resources :admins


  get "/lessons", to: "lessons#index", as: "lessons"
  get "/lesson/new", to: "lessons#new", as: "lesson_new"
  get "/lesson/:id", to: "lessons#show", as: "lesson_show"
  get "/lesson/:id/edit", to: "lessons#edit", as: "lesson_edit"
  post "/lessons", to: "lessons#create", as: "lesson_create"
  patch "/lesson/:id", to: "lessons#update", as: "lesson_update"
  delete "/lesson/:id", to: "lessons#destroy", as: "lesson_destroy"

  get "/users", to: "admins#users", as: "users"
  delete "/users/:id", to: "admins#admin_delete_user", as: "admin_delete_user"


end 

src/app/views/admins/_form.html.erb
<div class="container mt-5">

  <%= form_with(model: admin, local: true) do |form| %>
    <% if admin.errors.any? %>
      <div id="error_explanation">
        <!--<h2><%#= pluralize(admin.errors.count, "error") %> prohibited this student from being saved:</h2>-->

        <ul class="alert alert-warning list-style-none">
          <% admin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="container text-center">
      <%= image_tag user_avatar(@admin.user, 100), class: 'profile-avatar'%>
      <br>
      <%= form.file_field :avatar, accept: 'image/png,image/gif,image/jpeg', class: 'ml-5 mt-4' %>
    </div>


    <div class="row mt-4">
      <div class="form-group col">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control" %>
      </div>

      <div class="form-group col">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "form-control" %>
    </div>
    </div>


    <div class="actions">
      <%= form.submit 'Update', class: 'btn btn-primary' %>
    </div>
  <% end %>

</div>

src/app/views/admins/edit.html.erb
<%= render 'form', admin: @admin %>

<br>


<% if current_user.admin.id == @admin.id %>
  <%#= link_to 'Back', admins_path, class: 'btn btn-secondary' %>
  <%= link_to 'Change My Password', edit_user_registration_path, class: 'btn btn-outline-danger' %>
<% else %>
  <%#= link_to 'Back', admins_path, class: 'btn btn-secondary' %>
<% end %>

src/app/views/admins/index.html.erb
<h1 class="display-3">All Admins</h1>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @admins.each do |admin| %>
        <tr>
          <td><%= admin.first_name %></td>
          <td><%= admin.last_name %></td>
          <td><%= link_to 'Show', admin %></td>
          <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
          <td><%= link_to 'Delete', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if current_user.admin? %>
    <%= link_to 'New Admin', new_admin_path, class: 'btn btn-outline-primary' %>
  <% end %>

</div>

src/app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

src/app/views/admins/show.html copy.erb
<% if current_user.admin.id == @admin.id %>
  <%= link_to 'Edit My Account', edit_admin_path(@admin) %>
<% else %>
  <%= link_to "Edit Admin's Account", edit_admin_path(@admin) %>
<% end %>

<br>

<%= image_tag user_avatar(@admin.user, 100), class: 'profile-avatar'%>

<br>

<p>
  <strong>First name:</strong>
  <%= @admin.first_name.capitalize %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @admin.last_name.capitalize %>
</p>

<%= link_to 'Back', admins_path, class: 'btn btn-secondary' %>

src/app/views/admins/show.html.erb
<div class="container text-center mt-5">

  <%= render 'shared/show_page', person: @admin %>

</div>

src/app/views/admins/users.html.erb

<h1 class="display-3">All Users</h1>


<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">ID</th>
        <th scope="col">Student</th>
        <th scope="col">Instructor</th>
        <th scope="col">Admin</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.id %></td>
          <td><%= user&.student? ? user&.student&.first_name : "-"%></td>
          <td><%= user&.instructor? ? user&.instructor&.first_name : "-"%></td>
          <td><%= user&.admin? ? user&.admin&.first_name : "-"%></td>
          <td><%= link_to 'Delete', admin_delete_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


</div>
