src/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'publics#home', as: "home"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :instructors
  resources :students
  resources :admins


  get "/lessons", to: "lessons#index", as: "lessons"
  get "/lesson/new", to: "lessons#new", as: "lesson_new"
  get "/lesson/:id", to: "lessons#show", as: "lesson_show"
  get "/lesson/:id/edit", to: "lessons#edit", as: "lesson_edit"
  post "/lessons", to: "lessons#create", as: "lesson_create"
  patch "/lesson/:id", to: "lessons#update", as: "lesson_update"
  delete "/lesson/:id", to: "lessons#destroy", as: "lesson_destroy"

  get "/users", to: "admins#users", as: "users"
  delete "/users/:id", to: "admins#admin_delete_user", as: "admin_delete_user"


end 

src/app/models/instructor.rb
class Instructor < ApplicationRecord

  enum transmission: {manual: 0, automatic: 1}
  enum gender: {male: 0, female: 1}

  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_one_attached :avatar, dependent: :destroy
  has_many :lessons, dependent: :delete_all
  # has_many :comments, class_name: "comment", foreign_key: "comment_id"

  validates :first_name, presence: true, on: :update
  validates :last_name, presence: true, on: :update
  validate :address_check, on: :update
  validate :phone_number, on: :update
  validate :instructor_dob, on: :update
  
  private

  # custom validation for a phone number
  # a number must be present, must contain 10 digits, and must start in '04'
  # this should have been in a helper file somewhere to not repeate the function 
  def phone_number
    if phone != nil || phone != ""
      phone.to_s.delete('^0-9')
      if phone.empty?
        errors.add(:phone, "can't be blank")
      elsif phone.length != 10
        errors.add(:phone, "must be a 10 digit mobile number. eg. '0411222333'")
      elsif phone[0..1] != "04"
        errors.add(:phone, "must be a mobile number starting with '04'")
      end
    end
  end

  # custom validation for student dob
  # instructor must be older than 21 years to sign up
  def instructor_dob
    current_date = Date.today

    dob_year = dob.split('-')[0].to_i
    dob_month = dob.split('-')[1].to_i
    dob_day = dob.split('-')[2].to_i

    if current_date.year - 21 < dob_year
      errors.add(:instructor, "'s must be over 21 to use this app. If you are not, please delete your account you just created. You can find this in the 'Change My Password' button at the bottom of the page.")
    elsif current_date.year - 20 == dob_year and current_date.month < dob_month
      errors.add(:instructor, "'s must be over 21 to use this app. If you are not, please delete your account you just created. You can find this in the 'Change My Password' button at the bottom of the page.")
    elsif current_date.year - 20 == dob_year and current_date.month == dob_month and current_date.day < dob_day
      errors.add(:instructor, "'s must be over 21 to use this app. If you are not, please delete your account you just created. You can find this in the 'Change My Password' button at the bottom of the page.")
    end
  end

  # custom validation for address update
  # address must contain the australia part
  # this can be broken by simply typing 
    # test, Australia
  # but hopefully this one warning will stop them to select their address from the google api dropdown
  # this should have been in a helper to avoid repeating from student model
  def address_check
    unless address.include?(", Australia")
      errors.add(:address, "must be selected from Google Dropdown")
    end
  end


  
end

src/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  before_action :set_instructor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.order(:created_at).reverse_order.includes([:user])
    authorize! :read, @instructors, :message => "You do not have authorization to view that content."
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
    # get the instructor's upcoming and previous lessons for the jumbotron on the page
    @instructor = Instructor.find_by(id: params[:id])
    @upcoming = get_specific_lesson(@instructor, 'upcoming')[0]
    @previous = get_specific_lesson(@instructor, 'previous')[0]
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
    authorize! :read, @instructor, :message => "You do not have authorization to view that content."
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    # link the current user to the student when they finish filling in all their details
    @instructor = Instructor.new(instructor_params)
    @instructor.user = current_user
    authorize! :read, @instructor, :message => "You do not have authorization to view that content."

    if @instructor.save
      redirect_to edit_instructor_path, notice:  'Lesson successfully updated'
    else
      render :new, alert:  'Something went wrong and lesson was not updated.'
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit, alert: 'Something went wrong and details were not updated.' }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
      authorize! :read, @instructor, :message => "You do not have authorization to view that content."
    end

    # Only allow a list of trusted parameters through.
    def instructor_params
      # capitalise the first and last name on update
      # format the phone number by removing and non numeric characters from the string
      params[:instructor][:first_name].capitalize!
      params[:instructor][:last_name].capitalize!
      params[:instructor][:phone] = format_phone_number(params[:instructor][:phone])
      params.require(:instructor).permit(:first_name, :last_name, :address, :phone, :dob, :transmission, :gender, :avatar)
    end

end

src/app/helpers/instructors_helper.rb
module InstructorsHelper
end

src/app/views/instructors/_form.html.erb
<div class="container">

  <%= form_with(model: instructor, local: true, data: { controller: "places", action: "google-maps-callback@window->places#initMap" }) do |form| %>
    <% if instructor.errors.any? %>
      <div id="error_explanation">
        <!--<h2><%#= pluralize(instructor.errors.count, "error") %> prohibited this student from being saved:</h2>-->

        <ul class="alert alert-warning list-style-none">
          <% instructor.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="container text-center">
      <%= image_tag user_avatar(@instructor.user, 100), class: 'profile-avatar'%>
      <br>
      <%= form.file_field :avatar, accept: 'image/png,image/gif,image/jpeg', class: 'ml-5 mt-4' %>
    </div>


    <div class="row mt-5">
      <div class="form-group col">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control" %>
      </div>

      <div class="form-group col">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group form-check">
      <%= form.radio_button :gender, :male, class: "form-check-input" %>
      <%= form.label :gender, "Male", class: "form-check-label", value: :male %><br />
      <%= form.radio_button :gender, :female, class: "form-check-input" %>
      <%= form.label :gender, "Female", class: "form-check-label", value: :female %>
    </div>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.search_field :address, class: "form-control", data: { target: "places.field", action: "keydown->places#preventSubmit" } %>
    </div>

    <div class="form-group form-check">
      <%= form.radio_button :transmission, :manual, class: "form-check-input" %>
      <%= form.label :transmission, "Manual", class: "form-check-label", value: :manual %><br />
      <%= form.radio_button :transmission, :automatic, class: "form-check-input" %>
      <%= form.label :transmission, "Automatic", class: "form-check-label", value: :automatic %>
    </div>

    <div class="row">
    
      <div class="form-group col">
        <%= form.label :phone %>
        <%= form.text_field :phone, class: "form-control" %>
      </div>

      <div class="form-group col">
        <%= form.label :dob %>
        <%= form.date_field :dob, class: "form-control", value: @instructor.dob %>
      </div>

    </div>





      <div class="actions">
        <%= form.submit 'Update', class: 'btn btn-primary btn-lg' %>
      </div>



  <% end %>



</div>

src/app/views/instructors/edit.html.erb
<h1 class="display-3 text-center mb-4">Editing Your Details</h1>

<%= render 'form', instructor: @instructor %>

<br>

<div class="container">
  <% if current_user.instructor? %>
    <%= link_to 'Change My Password', edit_user_registration_path, class: 'btn btn-outline-danger'%>
  <% end %>
</div>

src/app/views/instructors/index.html.erb
<h1 class="display-3">All Instructors</h1>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Address</th>
        <th scope="col">Mobile</th>
        <th scope="col">Dob</th>
        <th scope="col">Transmission</th>
        <th scope="col">Gender</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @instructors.each do |instructor| %>
        <tr>
          <td><%= instructor.first_name.capitalize + ' ' + instructor.last_name.capitalize %></td>
          <td><%= instructor.user.email if instructor.user.email %></td>
          <td><%= instructor.address if instructor.address%></td>
          <td><%= "#{instructor.phone[0..3]} #{instructor.phone[4..6]} #{instructor.phone[7..9]}" %></td>
          <td><%= instructor.dob if instructor.dob %></td>
          <td><%= instructor.transmission.capitalize if instructor.transmission %></td>
          <td><%= instructor.gender.capitalize if instructor.gender %></td>
          <td><%= link_to 'Show', instructor %></td>
          <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
          <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if current_user.admin? %>
    <%#= link_to 'New Instructor', new_instructor_path, class: 'btn btn-outline-primary' %>
  <% end %>
</div>

src/app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

src/app/views/instructors/show.html copy.erb
<% if current_user.admin? %>
  <%= link_to "Edit Instructor's Account", edit_instructor_path(@instructor) %>
<% elsif current_user.instructor? %>
  <%= link_to 'Edit My Account', edit_instructor_path(@instructor) %>
<% end %>

<br>

<%= image_tag user_avatar(@instructor.user, 80), class: 'profile-avatar'%>

<br>

<p>
  <strong>Name:</strong>
  <%= if @instructor&.first_name&.empty? && @instructor&.last_name&.empty?
    "N/A"
  else
    @instructor&.first_name&.capitalize + ' ' + @instructor&.last_name&.capitalize
  end %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor&.user&.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @instructor&.address&.empty? ? "N/A" : @instructor&.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @instructor&.phone&.empty? ? "N/A" : "#{@instructor&.phone[0..3]} #{@instructor&.phone[4..6]} #{@instructor&.phone[7..9]}" %>
</p>

<p>
  <strong>Dob:</strong>
  <%= get_readable_date(@instructor&.dob, "without_day") %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @instructor&.transmission ? @instructor&.transmission&.capitalize : "N/A" %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @instructor&.gender ? @instructor&.gender&.capitalize : "N/A" %>
</p>


<% if current_user.admin? %>
  <%= link_to 'Show All Lessons', lessons_path, class: 'btn btn-outline-primary'%>
  <%= link_to 'Back', instructors_path, class: 'btn btn-secondary'%>
<% elsif current_user.instructor? %>
  <%= link_to 'Show All My Lessons', lessons_path, class: 'btn btn-outline-primary'%>
  <%= link_to 'Back', instructor_path(current_user&.instructor&.id), class: 'btn btn-secondary'%>
<% end %>

src/app/views/instructors/show.html.erb
<div class="container text-center mt-5">

  <%= render 'shared/show_page', person: @instructor, lesson: @lesson, upcoming: @upcoming, previous: @previous %>

</div>