src/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'publics#home', as: "home"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :instructors
  resources :students
  resources :admins


  get "/lessons", to: "lessons#index", as: "lessons"
  get "/lesson/new", to: "lessons#new", as: "lesson_new"
  get "/lesson/:id", to: "lessons#show", as: "lesson_show"
  get "/lesson/:id/edit", to: "lessons#edit", as: "lesson_edit"
  post "/lessons", to: "lessons#create", as: "lesson_create"
  patch "/lesson/:id", to: "lessons#update", as: "lesson_update"
  delete "/lesson/:id", to: "lessons#destroy", as: "lesson_destroy"

  get "/users", to: "admins#users", as: "users"
  delete "/users/:id", to: "admins#admin_delete_user", as: "admin_delete_user"


end 

src/app/views/shared/_footer.html.erb


<footer class="blog-footer">
  <div class="container">
    <span class="text-muted lead">&copy; <%= link_to 'Simon Curran 2020', 'https://www.simonmcurran.com/', target: :_blank %></span>
    <br>
    <span class="text-muted text-lowercase font-weight-light mt-2"> <%= link_to 'Twitter', 'https://twitter.com/simo_sultan', target: :_blank %> | <%= link_to 'GitHub', 'https://github.com/SimoSultan', target: :_blank %> | <%= link_to 'LinkedIn', 'https://www.linkedin.com/in/simo-sultan/', target: :_blank %> </span>
  </div>
</footer>


src/app/views/shared/_lesson_modal.html.erb








<!-- Vertically centered modal -->
<div id="lesson-modal" class="modal-dialog modal-dialog-centered" >

  <%#= render 'shared/lesson_modal', lesson: @lesson %>

  <div class="card" style="width: 18rem;">
    <img  class="card-img-top">
    <div class="card-body">
      <h5 class="card-title"> <%= @lesson&.date %></h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Cras justo odio</li>
      <li class="list-group-item">Dapibus ac facilisis in</li>
      <li class="list-group-item">Vestibulum at eros</li>
    </ul>
    <div class="card-body">
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>

</div>

src/app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top">

  <% unless current_page?(home_path) %>
    <%= link_to :back do %>
      <%= image_tag "capicon/277.png", class: 'back-button' %>
    <% end %>
  <% end %>

  <%= link_to home_path do %>
    <%= image_tag 'dlm-logo.png', class: 'navbar-logo'%>
  <% end %>

  <%= link_to "DLM", home_path, class: "navbar-brand navbar-brand-simo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarCollapse">
    
    <ul class="navbar-nav ml-auto nav-right">

      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li class="nav-item text-uppercase">
            <%= link_to 'Lessons', lessons_path, class: "nav-link" %>
          </li>
          <li class="nav-item text-uppercase">
            <%= link_to 'Students', students_path, class: "nav-link" %>
          </li>
          <li class="nav-item text-uppercase">
            <%= link_to 'Instructors', instructors_path, class: "nav-link" %>
          </li>
          <li class="nav-item text-uppercase">
            <%= link_to 'Admins', admins_path, class: "nav-link" %>
          </li>
          <li class="nav-item text-uppercase">
            <%= link_to 'Users', users_path, class: "nav-link" %>
          </li>
          <!--<li class="nav-item text-uppercase">
            <%#= link_to 'Edit Lesson Details (Future)', "#", class: "nav-link" %>
          </li>-->
          <li class="nav-item text-uppercase">
            <%= link_to "My Profile", admin_path(current_user.admin&.id), class: "nav-link" %>
          </li>
        <% elsif current_user.instructor? %>
          <li class="nav-item text-uppercase">
            <%= link_to 'My Lessons', lessons_path, class: "nav-link" %>
          </li>
          <!--<li class="nav-item text-uppercase">
            <%#= link_to 'My Calendar', "#", class: "nav-link" %>
          </li>-->
          <li class="nav-item text-uppercase">
            <%= link_to "My Profile", instructor_path(current_user.instructor&.id), class: "nav-link" %>
          </li>
        <% elsif current_user.student? %>
          <li class="nav-item text-uppercase">
            <%= link_to 'My Lessons', lessons_path, class: "nav-link" %>
          </li>
          <li class="nav-item text-uppercase">
            <%= link_to 'Book a Driving Lesson', lesson_new_path, class: "nav-link" %>
          </li>
          <li class="nav-item text-uppercase">
            <%= link_to "My Profile", student_path(current_user.student&.id), class: "nav-link" %>
          </li>
        <% end %>

      <% else %>
        <li class="nav-item text-uppercase">
          <%= link_to 'Book a Driving Lesson', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>

      <% if user_signed_in? %>
        <li class="nav-item ml-4 mr-4">
          <% if current_user.student? %>
            <%#= link_to "#{current_user.student&.first_name&.capitalize} #{current_user.student&.last_name&.capitalize}", student_path(current_user.student&.id), class: "nav-link" %>
            <%#= link_to "My Profile", student_path(current_user.student&.id), class: "nav-link" %>
            <%= link_to student_path(current_user.student&.id) do %>
              <%= image_tag user_avatar(current_user, 100), class: 'navbar-avatar inline'%>
            <% end %>
          <% elsif current_user.instructor?  %>
            <%#= link_to "#{current_user&.instructor&.first_name&.capitalize} #{current_user&.instructor&.last_name&.capitalize}", instructor_path(current_user&.instructor&.id), class: "nav-link" %>
            <%= link_to instructor_path(current_user.instructor&.id) do %>
              <%= image_tag user_avatar(current_user, 100), class: 'navbar-avatar'%>
            <% end %>
          <% elsif current_user.admin? %>
            <%#= link_to "#{current_user.admin&.first_name&.capitalize} #{current_user.admin&.last_name&.capitalize}", admin_path(current_user.admin&.id), class: "nav-link" %>
            <%= link_to admin_path(current_user.admin&.id) do %>
              <%= image_tag user_avatar(current_user, 100), class: 'navbar-avatar'%>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item text-uppercase">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link log-out-nav font-weight-bold" %>
        </li>
      <% else %>
        <li class="nav-item text-uppercase">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item text-uppercase">
          <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    
  </div>
</nav>

src/app/views/shared/_new_lesson.html.erb


<div class="card text-center">
  <h5 class="card-header">Book a Driving Lesson</h5>
  <div class="card-body">
    <%= form_with model: @lesson, local: true, url: lesson_create_path do |form| %>

      <div class="form-group row">
        <%= form.label :date, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.date_field :date, class: "form-control" %></div>
      </div>

      <div class="form-group row">
        <%= form.label :time, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.time_field :time, class: "form-control" %></div>
      </div>

      <% if false %>
      <div class="form-group row">
        <%= form.label :instructor, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6">
          <%= form.radio_button :instructor, :any, class: "form-check-input" %>
          <%= form.label :instructor, "Any Instructor", class: "form-check-label", value: :any %><br />
          <%= form.radio_button :instructor, :male, class: "form-check-input" %>
          <%= form.label :instructor, "Male", class: "form-check-label", value: :male %><br />
          <%= form.radio_button :instructor, :female, class: "form-check-input" %>
          <%= form.label :instructor, "Female", class: "form-check-label", value: :female %>
        </div>
      </div>
      <% end %>

      <% if current_user.admin? || current_user.instructor? %>
      <div class="form-group row">
        <%= form.label :student, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6">
          <%= form.collection_select :student_id, @students, :id, :first_name, {selected: "", disabled: "", prompt: "Select student"}, {value: :student, class: "form-control"} %>
        </div>
      </div>
      <% else %>
        <%= form.hidden_field :student_id, value: current_user.student.id %>
      <% end %>
 


      <div class="form-group row">
        <%= form.label :instructor, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6">
          <% if current_user.instructor? %>
            <%= form.collection_select :instructor_id, @instructors, :id, :first_name, {selected: "", disabled: "", prompt: "Select instructor"}, {value: current_user.instructor&.first_name, class: "form-control"} %>
          <% else %>
            <%= form.collection_select :instructor_id, @instructors, :id, :first_name, {selected: "", disabled: "", prompt: "Select instructor"}, {value: "", class: "form-control"} %>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :duration, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6">
          <%= form.select :duration, [['60 mins', 60], ['90 mins', 90], ['120 mins', 120]], {selected: "", disabled: "", prompt: "Select duration"}, {class: "form-control", value: :duration} %>
        </div>
      </div>

      <% if current_user.student? %>
       <div class="form-group row">
        <%= form.label :transmission, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.text_field :transmission, class: "form-control", disabled: true, value: current_user.student&.transmission&.capitalize %></div>
      </div>

      <div class="form-group row">
        <%= form.label :address, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.text_field :address, class: "form-control", disabled: true, value: current_user.student&.address %></div>
      </div>
      <% elsif current_user.admin? || current_user.instructor? %>
      <div class="form-group row">
        <%= form.label "Student Transmission", class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.text_field :transmission, class: "form-control", disabled: true, value: "prefilled in future update" %></div>
      </div>

      <div class="form-group row">
        <%= form.label "Student Address", class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.text_field :address, class: "form-control", disabled: true, value: "prefilled in future update" %></div>
      </div>
      <% end %>


      <div class="actions">
        <%= form.submit "BOOK", class: "btn btn-lg btn-primary" %>
      </div>
    <% end %>

  </div>
</div>


src/app/views/shared/_role_warning.html.erb

<div class="container mt-2">
  <h5>Developer Note:</h5>
  <p style="color:red; font-weight: bold;">I have left the role permissions in the form (even though I know I am not supposed to!!) because actually verifying an instructor's license number I would have to check it against Transport Department information. As this website is not intended for real use, then there's no point validating someone to be an instructor. And I wanted to leave it here so people can experience either role, for demonstration purposes only. So again...</p>
  <h6>PLEASE USE FAKE DATA WHEN USING THIS APPLICATION!!!!! YOU'VE BEEN WARNED.</h6>
</div>

<br>

src/app/views/shared/_show_page.html.erb


<div class="container text-center mt-1">


  <%= render 'shared/top_half_show', person: person %>


  <% if current_user.student? || current_user.instructor?%>

    <div class="jumbotron jumbotron-fluid mt-4 mb-3 text-left">
      <div class="container text-left">
        <% if upcoming %>
          <h5 class="inline">Upcoming Lesson</h5> <%= link_to 'More details', lesson_show_path(upcoming), class: 'ml-3 inline' %>
          <%#= link_to 'More details', lesson_show_path,  {remote: true, 'data-toggle' =>  "modal", 'data-target' => 'lesson-modal', class: ''}  %>
          <% if current_user.instructor? %>
            <p class="lead mb-1">A <%= upcoming&.duration %> min lesson with <%= upcoming&.student&.first_name %> on <%= get_readable_date(upcoming&.date&.to_s, "without_day") %> at <%= upcoming&.time&.strftime('%l:%M %P') %>, meeting at <%= upcoming&.student&.address %>.</p>
          <% else %>
            <p class="lead mb-1">A <%= upcoming&.duration %> min lesson with <%= upcoming&.instructor&.first_name %> on <%= get_readable_date(upcoming&.date&.to_s, "without_day") %> at <%= upcoming&.time&.strftime('%l:%M %P') %>, meeting at <%= @student.address %>.</p>
          <% end %>
          
        <% else %>
          <h5 class="inline">Upcoming Lesson</h5>
          <p class="lead mb-1">You have no upcoming lessons.</p>
        <% end %>
      </div>

      <div class="container text-right">
        <% if previous %>
          <%= link_to 'More details', lesson_show_path(previous), class: 'inline mr-3'%> <h5 class="inline">Previous Lesson</h5>
          
          <% if current_user.instructor? %>
            <p class="lead mb-1">A <%= previous&.duration %> min lesson with <%= previous&.student&.first_name %> on <%= get_readable_date(previous&.date&.to_s, "without_day") %>.</p>
          <% else %>
            <p class="lead mb-1">A <%= previous&.duration %> min lesson with <%= previous&.instructor&.first_name %> on <%= get_readable_date(previous&.date&.to_s, "without_day") %>.</p>
          <% end %>
          
        <% else %>
          <h5 class="inline">Previous Lesson</h5>
          <p class="lead mb-1">You have not had a lesson yet.</p>
        <% end %>
      </div>
    </div>

  <% end %>

  <div class="mt-3">
    <% if current_user.student? %>
      <%= link_to 'Show All My Lessons', lessons_path, class: 'btn btn-outline-primary mb-4' %>
    <% else %>
      <%= link_to 'Show All Lessons', lessons_path, class: 'btn btn-outline-primary mb-4' %>
    <% end %>
  </div>
  
  <% if current_user.student? %>
    <%= render 'shared/new_lesson', locals: {lesson: @lesson, instructors: @instructors} %>
  <% end %>

  <br>




</div>


src/app/views/shared/_signup2.html.erb
<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail">Email</label>
      <input type="email" class="form-control" id="inputEmail">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword">Password</label>
      <input type="password" class="form-control" id="inputPassword">
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6 mb-3">
      <label for="inputFirstName">First Name</label>
      <input type="text" class="form-control" id="inputFirstName" placeholder="Jane" required>
    </div>
    <div class="col-md-6 mb-3">
      <label for="inputLastName">Last Name</label>
      <input type="text" class="form-control" id="inputLastName" placeholder="Doe" required>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-2">
      <label for="inputDobDay">Day</label>
      <input type="text" class="form-control" id="inputDobDay" maxlength="2" placeholder="01" required>
    </div>
    <div class="form-group col-md-2">
      <label for="inputDobMonth">Month</label>
      <select id="inputDobMonth" class="form-control" required>
        <option selected>Choose...</option>
        <option value="01">January</option>
        <option value="02">February</option>
        <option value="03">March</option>
        <option value="04">April</option>
        <option value="05">May</option>
        <option value="06">June</option>
        <option value="07">July</option>
        <option value="08">August</option>
        <option value="09">September</option>
        <option value="10">October</option>
        <option value="11">November</option>
        <option value="12">December</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputDobYear">Year</label>
      <input type="text" class="form-control" id="inputDobYear" maxlength="4" placeholder="2000" required>
    </div>
  </div>
  <div class="form-group">
    <label for="inputMobile">Mobile Number</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="0400 111 222" maxlength="10" required>
  </div>
  <div class="form-group">
    <label for="inputAddress">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St" required>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">City</label>
      <input type="text" class="form-control" id="inputCity" required>
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control" required>
        <option selected>Choose...</option>
        <option value="QLD">QLD</option>
        <option value="VIC">VIC</option>
        <option value="NSW">NSW</option>
        <option value="NT">NT</option>
        <option value="ACT">ACT</option>
        <option value="WA">WA</option>
        <option value="SA">SA</option>
        <option value="TAS">TAS</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">Post Code</label>
      <input type="text" class="form-control" id="inputPostCode" maxlength="4" required>
    </div>
  </div>
  <div class="form-group col-md-4">
    <label for="inputTransmission">Transmission</label>
    <select id="inputTransmission" class="form-control" required>
      <option selected>Choose...</option>
      <option value="0">Manual</option>
      <option value="1">Automatic</option>
    </select>
  </div>

  
  <% if @details == "Instructor" %>
    <div class="form-group col-md-4">
      <label for="inputLicenseClass">License Class</label>
      <select id="inputLicenseClass" class="form-control" required>
        <option selected>Choose...</option>
        <option value="0">C</option>
        <option value="1">CA</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputYearStarted">Year Started Instructing</label>
      <input type="text" class="form-control" id="inputYearStarted" maxlength="4" placeholder="2007" required>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="inputBlueCard">Blue Card Number</label>
        <!--  <input type="text" class="form-control" id="inputBlueCard" maxlength="6" placeholder="999999" required> / 2 -->
      </div>
      <div class="form-group col-md-4">
        <label for="inputBlueCard">Blue Card Expiry</label>
        <!-- <input type="text" class="form-control" id="inputBlueCard" maxlength="6" placeholder="999999" required> -->
      </div>
    </div>  
  <% end %>
  

  <%= link_to 'Cancel', home_path, :class=> "btn btn-outline-primary" %>

  <button type="submit" class="btn btn-primary">Sign in</button>
</form>

src/app/views/shared/_slideout.html.erb


<!-- Modal -->
<div class="modal right fade" id="show_lesson_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel2">Right Sidebar</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>

      <div class="modal-body">

        <p>
          <strong>Instructor:</strong>
          <%= "#{lesson&.instructor&.first_name&.capitalize} #{lesson&.instructor&.last_name&.capitalize}" %>
          <%#= "#{@lesson&.instructor&.first_name&.capitalize} #{@lesson&.instructor&.last_name&.capitalize}" %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= lesson&.date %>
          <%#= @lesson.date %>
        </p>

        <p>
          <strong>Time:</strong>
          <%= lesson&.time.strftime('%H:%M') %>
          <%#= @lesson&.time.strftime('%H:%M') %>
        </p>

        <p>
          <strong>Duration:</strong>
          <%= "#{lesson&.duration} mins" %>
          <%#= "#{@lesson&.duration} mins" %>
        </p>

        <p>
          <strong>Address:</strong>
          <%= current_user.student.address.capitalize %>
        </p>

        <p>
          <strong>Transmission:</strong>
          <%= current_user.student.transmission.capitalize %>
        </p>

        <p>
          <strong>Cancelled:</strong>
          <%= lesson&.cancelled ? "Yes" : "No" %>
          <%#= @lesson&.cancelled ? "Yes" : "No" %>
        </p>


        <p>
          <strong>Payment:</strong>
          to-do
          <%#= @lesson.payment if @lesson.payment %>
        </p>

      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- modal-content -->
  </div><!-- modal-dialog -->
</div><!-- modal -->




src/app/views/shared/_top_half_show.html.erb
  
  
  <%= image_tag user_avatar(person.user, 100), class: 'profile-avatar text-center mt-5'%>
  <!--<p>Dob: <%#= get_readable_date(@student&.dob, "without_day") %></p>-->

  <br>

  <h2 class="mt-1">
    <%= if person&.first_name&.empty? && person&.last_name&.empty?
      "N/A"
    else
      person&.first_name&.capitalize + ' ' + person&.last_name&.capitalize
    end %>
  </h2>


  <div class="mt-1">
    <% if current_user.admin? %>
      
      <% if params[:controller] == "admins" %>
        <%= link_to 'Edit My Account', edit_admin_path(person) %>
      <% elsif params[:controller] == "instructors" %>
        <%= link_to "Edit Instructor's Account", edit_instructor_path(person) %>
      <% elsif params[:controller] == "students" %>
        <%= link_to "Edit Student's Account", edit_student_path(person) %>
      <% end %>
    
    <% elsif current_user.instructor? %>
      <%= link_to 'Edit My Account', edit_instructor_path(person) %>
    <% elsif current_user.student? %>
      <%= link_to 'Edit My Account', edit_student_path(person) %>
    <% end %>
  </div>

src/app/views/shared/_warning.html.erb
<h2 class="warning-header">WARNING: SITE IN DEVELOPMENT. If you wish to sign up to this site, please use fake data including email (there are no confirmation emails). Otherwise, feel free to use the email and password provided in the box below.</h2>