src/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'publics#home', as: "home"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :instructors
  resources :students
  resources :admins


  get "/lessons", to: "lessons#index", as: "lessons"
  get "/lesson/new", to: "lessons#new", as: "lesson_new"
  get "/lesson/:id", to: "lessons#show", as: "lesson_show"
  get "/lesson/:id/edit", to: "lessons#edit", as: "lesson_edit"
  post "/lessons", to: "lessons#create", as: "lesson_create"
  patch "/lesson/:id", to: "lessons#update", as: "lesson_update"
  delete "/lesson/:id", to: "lessons#destroy", as: "lesson_destroy"

  get "/users", to: "admins#users", as: "users"
  delete "/users/:id", to: "admins#admin_delete_user", as: "admin_delete_user"


end 

src/app/models/lesson.rb
class Lesson < ApplicationRecord

  require 'date'

  belongs_to :student
  belongs_to :instructor

  # has_one :payment, class_name: "payment", foreign_key: "payment_id"
  # has_many :comments, class_name: "comment", foreign_key: "reference_id"

  validate :lesson_date, on: :create
  validates :time, presence: true, on: :create
  validates :student, presence: true, on: :create
  validates :instructor, presence: true, on: :create
  validates :duration, presence: true, on: :create

  private

  def lesson_date
    today = Time.now

    if date < today
      errors.add(:date, "of lesson must be at least tomorrow's date.")
    end
  end

  # def lesson_time
  #   today = Time.now
  #   # hour = today.hour
  #   # minute = today.min
  #   if time < today
  #     errors.add(:time, "of lesson must be at least tomorrow's.")
  # end



end

src/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # authenticate a user before they can view any lesson information anywhere
  before_action :authenticate_user!

  def index
    @all_lessons = []
    # only query the database for relevant lesson information based on who is logged in
    # order that information by rever date and time, meaning closest time to current is at top
    # I don't need to authenticate the lessons variable because we are only querying base on current user 
    if current_user.student?
      @all_lessons = Lesson.where(student_id: current_user.student.id).order(:date, :time).reverse_order.includes([:student]).includes([:instructor])
    elsif current_user.instructor?
      @all_lessons = Lesson.where(instructor_id: current_user.instructor.id).order(:date, :time).reverse_order.includes([:student]).includes([:instructor])
    elsif current_user.admin?
      @all_lessons = Lesson.order(:date, :time).reverse_order.includes([:student]).includes([:instructor])
    end
    @all_lessons
    
    # authorize! :read, @all_lessons, :message => "You do not have authorization to view that content."
  end

  def new
    # get all instructors to display in the dropdown menu on the new lesson form
    # only get all the students if the current person is admin or instructor
    @lesson = Lesson.new
    @instructors = get_all_instructors()
    if current_user.admin? || current_user.instructor?
      @students = get_all_students()
    end
  end

  def edit
    # get all instructors to display in the dropdown menu on the edit lesson form
    # only get the information if the current person is admin or instructor
    # students cannot edit their own lessons
    if current_user.admin? || current_user.instructor?
      @lesson = Lesson.find_by(id: params[:id])
      @instructors = get_all_instructors()
      @students = get_all_students()
    end
  end

  def show
    @lesson = Lesson.find_by(id: params[:id])
  end


  def create

    if user_details_are_empty()
      # stop the user from creating a lesson until all their details are filled out
      # find this method in application controller
      if current_user.admin?
        redirect_to admin_path(current_user.admin.id), alert: 'Please fill in all user details before booking a lesson.'
      elsif current_user.instructor?
        redirect_to instructor_path(current_user.instructor.id), alert: 'Please fill in all user details before booking a lesson.'
      elsif current_user.student?
        redirect_to student_path(current_user.student.id), alert: 'Please fill in all user details before booking a lesson.'
      end
      return
    end

    @lesson = Lesson.new
    lesson_params = params[:lesson]

    @lesson.student_id = lesson_params[:student_id].to_i
    @lesson.instructor_id = lesson_params[:instructor_id].to_i
    @lesson.date = lesson_params[:date]
    @lesson.time = lesson_params[:time]
    @lesson.duration = lesson_params[:duration].to_i
    @lesson.cancelled = false

    puts "--------------------------"
    puts @lesson.inspect

    # return 

    if @lesson.save
      redirect_to lessons_path, notice: 'Lesson successfully created'
    else
      # if current_user.student? 
      #   redirect_to student_path(current_user.student.id), alert: 'Something went wrong and lesson was not created.'
      # elsif current_user.instructor?
      #   redirect_to instructor_path(current_user.instructor.id), alert: 'Something went wrong and lesson was not created.'
      # elsif current_user.admin?
      #   redirect_to admin_path(current_user.admin.id), alert: 'Something went wrong and lesson was not created.'
      # end

      if current_user.admin? || current_user.instructor?
        render :new, locals: {lesson: Lesson.new, instructors: get_all_instructors(), students: get_all_students()}, alert: "Date #{@lesson.errors[:date]}"
      else
        render :new, locals: {lesson: Lesson.new, instructors: get_all_instructors()}, alert: "Date #{@lesson.errors[:date]}"
      end
    end

  end

  def update
    id = params[:id]
    @lesson = Lesson.find_by(id: id)

    @lesson.date = params[:date]
    @lesson.time = params[:time]
    @lesson.instructor_id = params[:instructor_id].to_i
    @lesson.duration = params[:duration].to_i
    @lesson.cancelled = params[:cancelled]

    if @lesson.save
      redirect_to lessons_path, notice: 'Lesson successfully updated'
    else
      render :edit, alert: 'Something went wrong and lesson was not updated.'
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    id = params[:id]
    @lesson = Lesson.find_by(id: id)

    if @lesson.destroy
      redirect_to lessons_path, notice: 'Lesson successfully deleted'
    else
      redirect_to lessons_path, alert: 'Something went wrong and lesson was not deleted.'
    end

  end

  private

  def get_all_instructors
    # get only the instructors, ids, and first and last name to display in the dropdown for booking a lesson
    @instructors = Instructor.select("first_name", "last_name", "id").all
    @instructors.map do |ins|
      ins[:first_name] = "#{ins[:first_name]} #{ins[:last_name]}"
    end
    @instructors
  end

  def get_all_students
    # get only the get_all_students, ids, and first and last name to display in the dropdown for booking a lesson
    @students = Student.select("first_name", "last_name", "id").all
    @students.map do |stu|
      stu[:first_name] = "#{stu[:first_name]} #{stu[:last_name]}"
    end
    @students
  end

end

src/app/helpers/lessons_helper.rb
module LessonsHelper
end

src/app/views/lessons/_edit_lesson.html.erb
<h1>Edit Lesson</h1>

src/app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>

<div class="card text-center">
  <h5 class="card-header">Edit Driving Lesson</h5>
  <div class="card-body">
    <%= form_with model: @lesson, url: lesson_edit_path, method: "patch" do |form| %>

      <div class="form-group row">
        <%= form.label :date, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.date_field :date, value: @lesson.date, class: "form-control" %></div>
      </div>

      <div class="form-group row">
        <%= form.label :time, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.time_field :time, value: @lesson.time.strftime('%H:%M:%S'), class: "form-control"  %></div>
      </div>

      <% if false %>
      <div class="form-group row">
        <%= form.label :instructor, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6">
          <%= form.radio_button :instructor, :any, class: "form-check-input" %>
          <%= form.label :instructor, "Any Instructor", class: "form-check-label", value: :any %><br />
          <%= form.radio_button :instructor, :male, class: "form-check-input" %>
          <%= form.label :instructor, "Male", class: "form-check-label", value: :male %><br />
          <%= form.radio_button :instructor, :female, class: "form-check-input" %>
          <%= form.label :instructor, "Female", class: "form-check-label", value: :female %>
        </div>
      </div>
      <% end %>

      <div class="form-group row">
        <%= form.label :instructor, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6">
          <%= form.collection_select :instructor_id, @instructors, :id, :first_name, {value: :instructor}, {class: "form-control"} %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :duration, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6">
          <%= form.select :duration, [['60 mins', 60], ['90 mins', 90], ['120 mins', 120]], {}, {class: "form-control", value: :duration} %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :cancelled, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6">
          <%= form.radio_button :cancelled, false, class: "form-check-input", value: :cancelled %>
          <%= form.label :cancelled, "No", class: "form-check-label", value: false %><br />
          <%= form.radio_button :cancelled, true, class: "form-check-input", value: :cancelled %>
          <%= form.label :cancelled, "Yes", class: "form-check-label", value: true %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :transmission, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.text_field :transmission, class: "form-control", disabled: true, value: @lesson.student.transmission.capitalize %></div>
      </div>

      <div class="form-group row">
        <%= form.label :address, class: "col-sm-3 col-form-label text-left" %>
        <div class="col-sm-6"><%= form.text_field :address, class: "form-control", disabled: true, value: @lesson.student.address %></div>
      </div>

      <div class="actions">
        <%= form.submit "UPDATE", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'Back', lessons_path, class: "btn btn-secondary" %>

src/app/views/lessons/index.html.erb
<h1 class="display-3">All Lessons</h1>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Student</th>
        <th scope="col">Instructor</th>
        <th scope="col">Date</th>
        <th scope="col">Time</th>
        <th scope="col">Duration</th>
        <%# <th scope="col">Transmission</th> %>
        <th scope="col">Cancelled</th>
        <!--<th scope="col">Payment</th>-->
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% if @all_lessons.empty? %>
        <td>You have no booked lessons</td>
      <% end %>
      <% @all_lessons.each do |lesson| %>
        <tr>
          <td><%= lesson&.student&.first_name&.capitalize + ' ' + lesson&.student&.last_name&.capitalize %></td>
          <td><%= lesson&.instructor.first_name.capitalize + ' ' + lesson&.instructor&.last_name&.capitalize %></td>
          <td><%= lesson&.date%></td>
          <td><%= lesson&.time&.strftime('%H:%M')%></td>
          <td><%= "#{lesson&.duration} mins"%></td>
          <td><%= lesson&.cancelled ? "Yes": "No" %></td>
          <!--<td><%#= "to-do" %></td>-->
          <td><%= link_to 'More Details', lesson_show_path(lesson) %></td>
          <% if current_user.admin? || current_user.instructor? %>
          <td><%= link_to 'Edit', lesson_edit_path(lesson) %></td>
          <td><%= link_to 'Delete', lesson_destroy_path(lesson), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%#= render 'shared/slideout', lesson: lesson %>

  <%= link_to 'Book a New Lesson', lesson_new_path, class: 'btn btn-outline-primary' %>
</div>

src/app/views/lessons/lesson_modal.js.erb
$("#lesson-modal").find(".modal-content").html("<%= j (render 'show') %>");
$("#lesson-modal").modal();

src/app/views/lessons/new.html.erb

<h1 class="display-4">New Lesson</h1>

<% if @lesson.errors.any? %>
  <div id="error_explanation">
    <ul class="alert alert-warning list-style-none">
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'shared/new_lesson', locals: {lesson: @lesson, instructors: @instructors, students: @students} %>


<%# link_to 'Back', lessons_path, class: "btn btn-secondary" %>

src/app/views/lessons/show.html copy.erb

<p>
  <strong>Instructor:</strong>
  <%= @lesson.instructor.first_name.capitalize + ' ' + @lesson.instructor.last_name.capitalize if @lesson.instructor.first_name && @lesson.instructor.last_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @lesson.date if @lesson.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @lesson.time.strftime('%H:%M') if @lesson.time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= "#{@lesson.duration} mins" if @lesson.duration %>
</p>

<p>
  <strong>Address:</strong>
  <%= @lesson.student.address.capitalize %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @lesson.student.transmission.capitalize %>
</p>

<p>
  <strong>Cancelled:</strong>
  <%= @lesson.cancelled ? "Yes" : "No" %>
</p>


<p>
  <strong>Payment:</strong>
  to-do
  <%#= @lesson.payment if @lesson.payment %>
</p>



src/app/views/lessons/show.html.erb


<div class="container ">

  <div class="container text-center mt-1">
    <% if current_user.student? %>
      <%= render 'shared/top_half_show', person: @lesson.student %>
    <% elsif current_user.instructor? %>
      <%= render 'shared/top_half_show', person: @lesson.instructor %>
    <% end %>
  </div>

  <div class="container mt-5">
  
    <div id="lesson-show-card" class="card mb-3">
      <%= image_tag 'road.jpg', class: "card-img lesson-background" %>
      <div class="card-img-overlay">
        <h5 class="card-title display-2" style="color: white;">Lesson Details</h5>
      </div>

      <div class="card-body">
          <ul class="list-group list-group-flush col">
            <li class="list-group-item lead"><strong>Date:</strong> <%= get_readable_date(@lesson&.date, "with_day") %> </li>
            <li class="list-group-item lead""><strong>Time:</strong>  <%= @lesson&.time&.strftime('%l:%M %P')%> </li>
            <li class="list-group-item lead""><strong>Duration:</strong> <%= "#{@lesson&.duration} minutes" %> </li>
            <li class="list-group-item lead""><strong>Meet At:</strong> <%= get_readable_address(@lesson&.student&.address) %> </li>
            <li class="list-group-item lead""><strong>Instructor:</strong> <%= @lesson&.instructor&.first_name %> </li>
            <li class="list-group-item lead""><strong>Instructor Mobile:</strong> <%= get_readable_phone_number(@lesson&.instructor&.phone) %> </li>
          </ul>
      </div>
    </div>
  </div>
</div>


src/app/views/lessons/show_modal.js.erb
// populate modal
$('#show_lesson_modal').html("#{ escape_javascript(<%= render partial: 'lesson', locals: {lesson: @lesson} )}");

// render modal
$('#show_lesson_modal').modal('toggle');
$('#show_lesson_modal').modal('show');
//<script>
//    render 'shared/slideout', lesson: @lesson
//</script>
<%
=begin
var modal = document.getElementById("show_lesson_modal");
modal.innerHTML = ('#{ escape_javascript(<%= render partial: 'lesson', locals: {lesson: @lesson} )}');


var btn = document.getElementById("myBtn");
var span = document.getElementsByClassName("close")[0];
// When the user clicks the button, open the modal 
btn.onclick = function() {
  modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
=end
%>